bell_Electronics/Controllers/UserPanelController.cs
using bell_Electronics.Models;
using iTextSharp.text;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;


namespace bell_Electronics.Controllers
{
    public class UserPanelController : Controller
    {
        string db_con = ConfigurationManager.ConnectionStrings["LTTE"].ConnectionString;
        DbConext db = new DbConext();
        // GET: UserPanel
        [HttpGet]
        public ActionResult Login(string UserName)
        {
            if (Session["id"] == null)
            {
                var row = db.GetUser().Where(model => model.UserName == UserName).FirstOrDefault();
            }
            if (Session["id"] != null)
            {
                Session["id"] = null;
                Session["name"] = null;
                return RedirectToAction("Index", "Customer");
            }
            return View();
        }

        [HttpPost]
        public ActionResult Login(UsersModel um)
        {

            if (Session["id"] == null)
            {
                var data = db.GetUser().Where(model => model.UserName == um.UserName && model.Password == um.Password).FirstOrDefault();
                if (data != null)
                {
                    Session["id"] = um.UserName;
                    Session["usname"] = um.Name;
                    return RedirectToAction("Index", "Customer");
                }
                else if (um.UserName == "Admin" && um.Password == "LTTE")
                {
                    Session["id"] = um.UserName;
                    Session["usname"] = um.Name;
                    return RedirectToAction("Index", "Category");
                }
                else
                {
                    ViewBag.Showmsg = "Invalid Email id or Password";
                    ModelState.Clear();
                    return View();
                }
            }
            else if (Session["id"] != null)
            {
                Session["id"] = null;
                Session["name"] = null;
            }
            return View();
        }

        [HttpGet]
        public ActionResult UserRegistraion()
        {
            if (Session["id"] == null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("UserDetails");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UserRegistraion(UsersModel usm)
        {
            try
            {
                using (SqlConnection con = new SqlConnection(db_con))
                {
                    SqlCommand cmd = new SqlCommand("sp_User_CURD", con);
                    cmd.CommandType = CommandType.StoredProcedure;
                    con.Open();
                    cmd.Parameters.AddWithValue("@Action", "INSERT");
                    cmd.Parameters.AddWithValue("@Name", usm.Name);
                    cmd.Parameters.AddWithValue("@MobileNo", usm.MobileNo);
                    cmd.Parameters.AddWithValue("@Email", usm.Email);
                    cmd.Parameters.AddWithValue("@UserName", usm.UserName);
                    cmd.Parameters.AddWithValue("@Password", usm.Password);
                    cmd.ExecuteNonQuery();
                    con.Close();
                }
                TempData["success"] = "User Data Registration Successfully!!!";
                return RedirectToAction("Login");
            }
            catch (Exception)
            {
                return View();
            }
        }


        public ActionResult UserDetails()
        {
            try
            {
                if (Session["id"] != null)
                {
                    UsersModel usmd = new UsersModel();
                    using (SqlConnection con = new SqlConnection(db_con))
                    {
                        SqlCommand cmd = new SqlCommand("sp_User_CURD", con);
                        cmd.CommandType = CommandType.StoredProcedure;
                        con.Open();
                        cmd.Parameters.AddWithValue("@Action", "FETCH");
                        cmd.Parameters.AddWithValue("@UserName", Session["id"]);
                        SqlDataReader reader = cmd.ExecuteReader();
                        while (reader.Read())
                        {
                            usmd = new UsersModel
                            {
                                id = Convert.ToInt32(reader["id"]),
                                Name = reader["Name"].ToString(),
                                MobileNo = reader["MobileNo"].ToString(),
                                Email = reader["Email"].ToString(),
                                UserName = reader["UserName"].ToString(),
                                Password = reader["Password"].ToString(),
                            };
                        }
                        con.Close();
                        return PartialView(usmd);
                    }
                }
                else
                {
                    return RedirectToAction("Login");
                }
            }
            catch (Exception)
            {
                return View();
            }

        }

        public ActionResult UserEdit()
        {
            if (Session["id"] != null)
            {
                UsersModel usmd = new UsersModel();
                using (SqlConnection con = new SqlConnection(db_con))
                {
                    SqlCommand cmd = new SqlCommand("sp_User_CURD", con);
                    cmd.CommandType = CommandType.StoredProcedure;
                    con.Open();
                    cmd.Parameters.AddWithValue("@Action", "FETCH");
                    cmd.Parameters.AddWithValue("@UserName", Session["id"]);
                    SqlDataReader reader = cmd.ExecuteReader();
                    while (reader.Read())
                    {
                        usmd = new UsersModel
                        {
                            id = Convert.ToInt32(reader["id"]),
                            Name = reader["Name"].ToString(),
                            MobileNo = reader["MobileNo"].ToString(),
                            Email = reader["Email"].ToString(),
                            UserName = reader["UserName"].ToString(),
                            Password = reader["Password"].ToString(),
                        };
                    }
                    con.Close();
                    return PartialView(usmd);
                }
            }
            else
            {
                return RedirectToAction("Login");
            }

        }

        [HttpPost]
        public ActionResult UserEdit(UsersModel usmod)
        {
            if (Session["id"] != null)
            {
                try
                {
                    using (SqlConnection con = new SqlConnection(db_con))
                    {
                        SqlCommand cmd = new SqlCommand("sp_User_CURD", con);
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.Parameters.AddWithValue("@Action", "UPDATE");
                        cmd.Parameters.AddWithValue("@UserName", Session["id"]);
                        cmd.Parameters.AddWithValue("@Name", usmod.Name);
                        cmd.Parameters.AddWithValue("@MobileNo", usmod.MobileNo);
                        cmd.Parameters.AddWithValue("@Email", usmod.Email);
                        cmd.Parameters.AddWithValue("@Password", usmod.Password);
                        con.Open();
                        cmd.ExecuteNonQuery();
                        con.Close();
                    }

                    TempData["userSuss"] = usmod.Name + " User Data Updated Successfully!!!!";
                    return RedirectToAction("UserDetails");
                }
                catch (Exception ex)
                {
                    ViewBag.error = "Error" + ex;
                }
            }
            else
            {
                return RedirectToAction("Login");
            }
            return View();
        }

        public ActionResult OrderDetails()
        {
            if (Session["id"] != null)
            {
                List<Order> ordlst = new List<Order>();
                using (SqlConnection con = new SqlConnection(db_con))
                {

                    con.Open();
                    SqlCommand cmd = new SqlCommand("sp_Order_CURD", con);
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@Action", "SELECT");
                    cmd.Parameters.AddWithValue("@UserName", Session["id"]);
                    SqlDataReader reader = cmd.ExecuteReader();
                    while (reader.Read())
                    {
                        ordlst.Add(new Order
                        {
                            OrderNo = reader["OrderNo"].ToString(),
                            ProductsId = Convert.ToInt32(reader["ProductsID"].ToString()),
                            Quantity = Convert.ToInt32(reader["Quantity"].ToString()),
                            UserName = reader["UserName"].ToString(),
                            Status = reader["Status"].ToString(),
                            PaymentId = reader["PaymentID"].ToString(),
                            OrderDate = reader["OrderDate"].ToString(),
                            ProductsName = reader["ProductsName"].ToString(),
                            PrdimageUrl = reader["PrdimageUrl"].ToString()
                        });
                    }
                    con.Close();
                return View(ordlst);
                }
            }
            else
            {
                return RedirectToAction("Login");
            }
        }
    }
}

bell_Electronics/Views/UserPanel/Login.cshtml
@model bell_Electronics.Models.UsersModel

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LayoutDefault.cshtml";
}

@if (TempData["success"] != null)
{
    <script src="~/Scripts/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script type="text/javascript">
     toastr.success('@TempData["success"]');
    </script>
}


@using (Html.BeginForm("Login",
                        "UserPanel",
                        FormMethod.Post,
                        new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="section">
        <div class="container">
            <div class="card shadow mt-2">
                <div class="card-header py-3 ">
                    <h2 class="m-0 font-weight-bold text-success" style="text-align:center">Login</h2>
                </div>
                <div class="card-body">
                    <div class="row mb-3">
                        <div class="col-md-6 ms-lg-5 mt-5">

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                            <div class="text align-content-center">
                                <div class="mb-3">
                                    <h4> User Id</h4>
                                    @Html.TextBoxFor(model => model.UserName, new  { @class = "form-control",placeholder="User Name" } )
                                    @Html.ValidationMessageFor(model => model.UserName, "*", new { @class = "text-danger" })

                                </div>

                                <div class="mb-3">
                                    <h4>Password</h4>
                                    @Html.PasswordFor(model => model.Password, new { @class = "form-control",type="password",placeholder="Password" } )
                                    @Html.ValidationMessageFor(model => model.Password, "*", new { @class = "text-danger" })

                                </div>
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Login" class="btn btn-success me-3" />
                                    <a href="~//UserPanel/UserRegistraion" class="btn btn-info">Are you New User ?</a> 
                                </div>
                            </div>

                        </div>
                        <div class="col mt-5">
                            <div class="form-group">
                                <img src="https://rurutek.com/jio/assets/img/login-animate.gif" class="img-thumbnail rounded-3" style="width:400px;height:300px" />
                            </div>
                        </div>
                    </div>
                </div>
                <br />
                <div class="row ms-lg-5">
                    @*@Html.Raw(ViewBag.Showmsg);*@
                    <div class="form-group">
                        <p style="color:red">@ViewBag.Showmsg</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
}


<div>
    <a href="~//Customer/Index" class="btn btn-primary">Back to Home</a>
</div>

bell_Electronics/Views/UserPanel/OrderDetails.cshtml
@model IEnumerable<bell_Electronics.Models.Order>
@{
    ViewBag.Title = "OrderDetails";
    Layout = "~/Views/Shared/_LayoutDefault.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h2 class="m-0 font-weight-bold text-primary" style="text-align:center">OrderDetails Lists</h2>
    </div>
    <div class="card-body">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <tr>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.OrderNo)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.ProductsName)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.PrdimageUrl)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.Quantity)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.UserName)
                </th>
                <th class="text-center">
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                @*<th class="text-center">
                    @Html.DisplayNameFor(model => model.PaymentId)
                </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.OrderDate)
                </th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center" width="10%">
                        @Html.DisplayFor(modelItem => item.OrderNo)
                    </td>
                    <td class="text-center" width="20%">
                        @Html.DisplayFor(modelItem => item.ProductsName)
                    </td>
                    <td class="text-center" width="20%">
                        <img src="@Url.Content(item.PrdimageUrl)" style=" height:100px;width:100px ;border-radius:10px 10px 10px 10px" />
                    </td>
                    <td class="text-center" width="10%">
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td class="text-center" width="10%">
                        @Html.DisplayFor(modelItem => item.UserName)
                    </td>
                    @*<td class="text-center" width="10%">
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>*@

                    <td class="text-center" width="10%">
                        <span class="@(item.Status=="Pending" ? "badge rounded-pill bg-danger":"badge rounded-pill bg-success")"> @(item.Status) </span>

                        @Html.HiddenFor(modelItem => item.Status)

                    </td>

                    <td class="text-center" width="10%">
                        @Html.DisplayFor(modelItem => item.OrderDate)
                    </td>

                </tr>
            }
        </table>
    </div>
</div>

bell_Electronics/Views/UserPanel/UserDetails.cshtml
@model bell_Electronics.Models.UsersModel
@{
    ViewBag.Title = "UserDetails";
    Layout = "~/Views/Shared/_LayoutDefault.cshtml";
}

@if (TempData["userSuss"] != null)
{
    <script src="~/Scripts/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script type="text/javascript">
     toastr.success('@TempData["userSuss"]');
    </script>
}


<div class="container mt-3">
    <div class="card shadow mb-4">
        <div class="card-header py-3 ">
            <h2 class="m-0 font-weight-bold text-primary" style="text-align:center">User Details</h2>
        </div>
        <div class="card-body">
            <div class="row justify-content-around">
                <div class="col-md-7 text-center">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.id)

                    <div class="row mt-3">
                        <div class="col-sm-3 col-md-4 col-5">
                            <h3 style="font-weight: bold;">Name</h3>
                        </div>
                        <div class="col-md-5 col-6">
                            <h4> @(Model.Name) </h4>
                        </div>
                    </div>
                    <hr style="border: 1px solid black;" />
                    <div class="row">
                        <div class="col-sm-3 col-md-4 col-5">
                            <h3 style="font-weight: bold;">Mobile</h3>
                        </div>
                        <div class="col-md-5 col-6">
                            <h4> @(Model.MobileNo) </h4>
                        </div>
                    </div>
                    <hr style="border: 1px solid black;" />

                    <div class="row">
                        <div class="col-sm-3 col-md-4 col-5">
                            <h3 style="font-weight: bold;">Email</h3>
                        </div>
                        <div class="col-md-5 col-6">
                            <h4> @(Model.Email) </h4>
                        </div>
                    </div>
                    <hr style="border: 1px solid black;" />

                    <div class="row">
                        <div class="col-sm-3 col-md-4 col-5">
                            <h3 style="font-weight: bold;">User Name  </h3>
                        </div>
                        <div class="col-md-5 col-6">
                            <h4> @(Model.UserName) </h4>
                        </div>
                    </div>
                    <hr style="border: 1px solid black;" />
                    <div class="row">
                        <div class="col-sm-3 col-md-4 col-5">
                            <h3 style="font-weight: bold;">Password </h3>
                        </div>
                        <div class="col-md-5 col-6">
                            <h4> @(Model.Password) </h4>
                        </div>
                    </div>
                    <hr style="border: 1px solid black;" />
                </div>
                <div class="col-md-5">
                    <div class="product-details">
                        <img src="https://cdn.dribbble.com/users/8619169/screenshots/16116886/media/a63d64bcccad878cb9dfdb9a9f6b6416.gif" style="width:100%" />
                    </div>
                </div>
            </div>
        </div>
        <dvi class="card-footer">
            <div class="row">
                <div class="col-md-6">
                    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                        <a href="~//Customer/AllProductsView" class="btn btn-primary"> Back to home</a>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                        <a class="btn btn-warning" href="~//UserPanel/UserEdit?id=@Model.UserName"> Edit User</a>
                    </div>
                </div>
            </div>
        </dvi>
    </div>
</div>






@*<div class="form-group">
        <p style="color:red">@ViewBag.error</p>
    </div>*@

bell_Electronics/Views/UserPanel/UserEdit.cshtml
@model bell_Electronics.Models.UsersModel
@{
    ViewBag.Title = "UserEdit";
    Layout = "~/Views/Shared/_LayoutDefault.cshtml";
}




@using (Html.BeginForm("UserEdit",
                           "UserPanel", FormMethod.Post,
new { enctype = "multipart/form-data" }))
{

    @Html.AntiForgeryToken()
    <div class="container mt-3">
        <div class="card shadow mb-4">
            <div class="card-header py-3 ">
                <h2 class="m-0 font-weight-bold text-primary" style="text-align:center">  @Session["id"]  Editer</h2>
            </div>
            <div class="card-body">
                <div class="row justify-content-around">
                    <div class="col-md-5">
                        <div class="product-details">
                            <img src="https://cdn.pixabay.com/animation/2023/06/30/07/30/07-30-05-456_512.gif" style="width:100%" />
                        </div>
                    </div>
                    <div class="col-md-7 text-center">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.id)

                        <div class="row mt-3">
                            <div class="col-sm-3 col-md-4 col-5">
                                <h3 style="font-weight: bold;">Name</h3>
                            </div>
                            <div class="col-md-5 col-6">
                                @Html.TextBoxFor(Model => Model.Name, new { @class = "form-control input-lg" })

                            </div>
                        </div>
                        <hr style="border: 1px solid black;" />
                        <div class="row">
                            <div class="col-sm-3 col-md-4 col-5">
                                <h3 style="font-weight: bold;">Mobile</h3>
                            </div>
                            <div class="col-md-5 col-6">
                                @Html.TextBoxFor(Model => Model.MobileNo, new { @class = "form-control input-lg" })
                            </div>
                        </div>
                        <hr style="border: 1px solid black;" />

                        <div class="row">
                            <div class="col-sm-3 col-md-4 col-5">
                                <h3 style="font-weight: bold;">Email</h3>
                            </div>
                            <div class="col-md-5 col-6">
                                @Html.TextBoxFor(Model => Model.Email, new { @class = "form-control input-lg" })
                            </div>
                        </div>
                        <hr style="border: 1px solid black;" />
                        <div class="row">
                            <div class="col-sm-3 col-md-4 col-5">
                                <h3 style="font-weight: bold;">Password</h3>
                            </div>
                            <div class="col-md-5 col-6">
                                @Html.TextBoxFor(Model => Model.Password, new { @class = "form-control input-lg" })
                            </div>
                        </div>
                        <hr style="border: 1px solid black;" />
                    </div>

                </div>
            </div>
            <dvi class="card-footer">
                <div class="row">
                    <div class="col-md-6">
                        <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                            <a href="~//UserPanel/UserDetails" class="btn btn-primary"> Back</a>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                            <input class="btn btn-warning" type="submit" value="Submit" />
                        </div>
                    </div>
                </div>
            </dvi>
        </div>
    </div>
}
<div class="form-group">
    <p style="color:red">@ViewBag.error</p>
</div>

bell_Electronics/Views/UserPanel/UserRegistraion.cshtml
@model bell_Electronics.Models.UsersModel
@{
    ViewBag.Title = "UserRegistraion";
    Layout = "~/Views/Shared/_LayoutDefault.cshtml";
}

@using (Html.BeginForm("UserRegistraion",
                        "UserPanel",
                        FormMethod.Post,
                        new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="section">
        <div class="container">
            <div class="card shadow rounded-3">
                <div class="card-header py-3 ">
                    <h2 class="m-0 font-weight-bold text-primary" style="text-align:center">New User Registration</h2>
                </div>
                <div class="card-body">
                    <div class="row mb-3">
                    
                        <div class="col-md-6 ms-lg-5 mt-5">

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div>
                              
                                <h4 class="">Name</h4>


                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control border border-info" })

                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>

                            <div class="mt-3">
                              
                                <h4 class="">Moblie</h4>

                                @Html.TextBoxFor(model => model.MobileNo, new { @class = "form-control border border-info", })

                                @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })

                            </div>

                            <div class="mt-3">
                                <h4 class="">Email</h4>
                                @Html.TextBoxFor(model => model.Email, new { @class = "form-control border border-info", })

                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                            <div class="mt-3">
                                <h4 class="">Username</h4>

                                @Html.TextBoxFor(model => model.UserName, new { @class = "form-control border border-info" })

                                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                            </div>
                            <div class="mt-3 mb-4">
                                <h4 class="">Password</h4>

                                @Html.PasswordFor(model => model.Password, new { @class = "form-control border border-info" })

                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>

                        </div>
                        <div class="col">
                            <div class="form-group">
                                <img src="~/Images/registrationpic.jpg" class="img-thumbnail rounded-5" style="width:70%" />
                            </div>
                        </div>


                        <div class="card-footer">
                        <div class="row">
                            <div class="col-md-2">
                                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                    <a href="~/UserPanel/Login" class="btn btn-info">Already Register</a>
                                </div>
                            </div>
                            <div class="col-md-10">
                                <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                                    <input type="submit" value="Submit       " class="btn btn-success mt-1" />
                                </div>
                            </div>
                        </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <br />
       
    </div>



}